### ISSUE TITLE
KeyError: 'createdDate' on private / restricted share documents instead of graceful exit.

### ISSUE THREAD

**Issue by AtomicMaya** [Malfrats/xeuledoc#1]
The program raises errors on private / restricted URL docs instead of exiting gracefully.

Example doc: `https://docs.google.com/document/d/1mn1HX2YP-mp0GILNZQfks0d69l3OqWLScdDBbGd06IE/edit?usp=sharing`

Result: 
```bash
xeuledoc https://docs.google.com/document/d/1mn1HX2YP-mp0GILNZQfks0d69l3OqWLScdDBbGd06IE/edit?usp=sharing
Twitter : @MalfratsInd
Github : https://github.com/Malfrats/xeuledoc

Document ID : 1mn1HX2YP-mp0GILNZQfks0d69l3OqWLScdDBbGd06IE

Traceback (most recent call last):
  File "/home/kali/.local/bin/xeuledoc", line 8, in <module>
    sys.exit(main())
  File "/home/kali/.local/lib/python3.8/site-packages/xeuledoc/core.py", line 74, in main
    doc_hunt(sys.argv[1])
  File "/home/kali/.local/lib/python3.8/site-packages/xeuledoc/core.py", line 29, in doc_hunt
    created_date = datetime.strptime(data["createdDate"], '%Y-%m-%dT%H:%M:%S.%fz')
KeyError: 'createdDate'
```

Thanks.

**Comment by megadose** [comment]
This is fixed, it is because the file is not public or does not exist.
https://github.com/Malfrats/xeuledoc/commit/7288d601983a4f822aba47f6827135fee5c4a46a
